development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: brightonruby_development
  host: localhost
  username: root
  password:
  pool: 5

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: brightonruby_test
  host: localhost
  username: root
  password:
  pool: 5


cucumber:
  <<: *test